In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#Carga desde un archivo .csv sin indice
data = pd.read_csv('Citas_Digital_Filtrado.csv')
data.head(5)

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?,Unnamed: 15
0,Saul,NaN,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s...",Comenta que no se le hizo atractivo el arrenda...
1,Saul,NaN,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso,NaN
2,Saul,NaN,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso,Se le manda msj de seguimiento 03/05/2025
3,Saul,NaN,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as...",NaN
4,Saul,NaN,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...,Por el detalle del carbilink compro en otra ma...

In [21]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 676 entries, 0 to 675
Data columns (total 16 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   BDC                                       660 non-null    str
 1   Fecha                                     75 non-null     str
 2   Nombre Cliente                            655 non-null    str
 3   Telefono                                  2 non-null      str
 4   Estatus de Lead                           641 non-null    str
 5   Potencial de compra                       602 non-null    str
 6   PDM                                       675 non-null    float64
 7   SDC                                       674 non-null    float64
 8   Venta                                     671 non-null    float64
 9   Asesor Asignado                           644 non-null    str
 10  ¿Por que no ha visitado la agencia?       493 non-null    str
 11  ¿Por que no hay solicitud de credito?     379 non-null    str
 12  ¿Por que no hubo prueba de manejo ?       355 non-null    str
 13  ¿Por que no hubo proceso wow?             364 non-null    str
 14  ¿Por que se asigno antes de vistar piso?  353 non-null    str
 15  Unnamed: 15                               16 non-null     str
dtypes: float64(3), str(13)
memory usage: 84.6 KB

In [4]:

data2 = data.drop(['Fecha','Telefono ','Unnamed: 15'], axis=1)
data2

,BDC,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?
0,Saul,Guillermo,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s..."
1,Saul,Roberto,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso
2,Saul,Irving,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso
3,Saul,Oswaldo,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as..."
4,Saul,Rodrigo,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,Ana,Maira Escalante,Activo,0.8,1.0,1.0,0.0,Pedro Antonio,NaN,NaN,NaN,NaN,NaN
672,Ignacio,Zaira Macip,Activo,0.5,0.0,0.0,0.0,Aurelio,NaN,NaN,NaN,NaN,NaN
673,Ignacio,Julio Hernandez,Activo,0.5,1.0,0.0,0.0,Victor,NaN,NaN,NaN,NaN,NaN
674,Ignacio,Xhunaxhi Vicente,Activo,1,1.0,1.0,1.0,Ignacio,NaN,NaN,NaN,NaN,NaN
675,Ignacio,DR Jairo Rodriguez Farias,Activo,1,1.0,1.0,1.0,Victor,NaN,NaN,NaN,NaN,NaN

In [5]:
valores_nulos = data2.isnull().sum()
valores_nulos

BDC                                          16
Nombre Cliente                               21
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [6]:
#Realizamos una copia del dataframe
data3 = data2.copy()

In [13]:
data3["Venta"] = data3["Venta"].fillna(0)

In [14]:
data3["SDC"] = data3["SDC"].fillna(round(data2["SDC"].median(),1))
data3["PDM"] = data3["PDM"].fillna(round(data2["PDM"].mean(),1))

In [15]:
valores_nulos = data3.isnull().sum()
valores_nulos

BDC                                          16
Nombre Cliente                               21
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           0
SDC                                           0
Venta                                         0
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
dtype: int64

In [16]:
data3["¿Por que no ha visitado la agencia?"] = data3["¿Por que no ha visitado la agencia?"].fillna("No aplica")
data3["¿Por que no hay solicitud de credito?"] = data3["¿Por que no hay solicitud de credito?"].fillna("No aplica")
data3["¿Por que no hubo prueba de manejo ?"] = data3["¿Por que no hubo prueba de manejo ?"].fillna("No aplica")
data3["¿Por que no hubo proceso wow?"] = data3["¿Por que no hubo proceso wow?"].fillna("No aplica")
data3["¿Por que se asigno antes de vistar piso?"] = data3["¿Por que se asigno antes de vistar piso?"].fillna("No aplica")

In [17]:
valores_nulos = data3.isnull().sum()
valores_nulos

BDC                                         16
Nombre Cliente                              21
Estatus de Lead                             35
Potencial de compra                         74
PDM                                          0
SDC                                          0
Venta                                        0
Asesor Asignado                             32
¿Por que no ha visitado la agencia?          0
¿Por que no hay solicitud de credito?        0
¿Por que no hubo prueba de manejo ?          0
¿Por que no hubo proceso wow?                0
¿Por que se asigno antes de vistar piso?     0
dtype: int64

In [18]:
data3 = data3.dropna(subset=['BDC ','Nombre Cliente ','Estatus de Lead','Potencial de compra','Asesor Asignado'])
data3

,BDC,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?
0,Saul,Guillermo,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s..."
1,Saul,Roberto,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso
2,Saul,Irving,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso
3,Saul,Oswaldo,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as..."
4,Saul,Rodrigo,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,Ana,Maira Escalante,Activo,0.8,1.0,1.0,0.0,Pedro Antonio,No aplica,No aplica,No aplica,No aplica,No aplica
672,Ignacio,Zaira Macip,Activo,0.5,0.0,0.0,0.0,Aurelio,No aplica,No aplica,No aplica,No aplica,No aplica
673,Ignacio,Julio Hernandez,Activo,0.5,1.0,0.0,0.0,Victor,No aplica,No aplica,No aplica,No aplica,No aplica
674,Ignacio,Xhunaxhi Vicente,Activo,1,1.0,1.0,1.0,Ignacio,No aplica,No aplica,No aplica,No aplica,No aplica
675,Ignacio,DR Jairo Rodriguez Farias,Activo,1,1.0,1.0,1.0,Victor,No aplica,No aplica,No aplica,No aplica,No aplica

In [19]:
valores_nulos = data3.isnull().sum().sum()
valores_nulos

np.int64(0)

In [20]:
data3.info()

<class 'pandas.DataFrame'>
Index: 581 entries, 0 to 675
Data columns (total 13 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   BDC                                       581 non-null    str
 1   Nombre Cliente                            581 non-null    str
 2   Estatus de Lead                           581 non-null    str
 3   Potencial de compra                       581 non-null    str
 4   PDM                                       581 non-null    float64
 5   SDC                                       581 non-null    float64
 6   Venta                                     581 non-null    float64
 7   Asesor Asignado                           581 non-null    str
 8   ¿Por que no ha visitado la agencia?       581 non-null    str
 9   ¿Por que no hay solicitud de credito?     581 non-null    str
 10  ¿Por que no hubo prueba de manejo ?       581 non-null    str
 11  ¿Por que no hubo proceso wow?             581 non-null    str
 12  ¿Por que se asigno antes de vistar piso?  581 non-null    str
dtypes: float64(3), str(10)
memory usage: 63.5 KB

In [22]:
data3.to_csv("Citas_Digital_sin_nulos.csv", index=False)